### ISSUE TITLE
【已解决】大佬这个怎么下载呀，，，不太熟悉github

### ISSUE THREAD

**Issue by iBesokuse** [winezer0/APIFinderPlus#1]

**Comment by winezer0** [comment]
开了自动编译 在actions里面下载 https://github.com/winezer0/APIFinderPlus/actions

当前1.0.6下载链接 https://github.com/winezer0/APIFinderPlus/actions/runs/11219498329/artifacts/2024874347

**Comment by winezer0** [comment]
下载地址
访问 https://github.com/winezer0/APIFinderPlus/actions

-> 最新工作流【绿色表示有效】 
-> 点击 Summary 
-> 滑倒最下面下载 jar-with-dependencies  
-> 解压即可
