### ISSUE TITLE
【已解决】太难用了把，开一段时间直接吃我20多G空间，系统提示空间不够排查才发现，全是这插件的数据

### ISSUE THREAD

**Issue by qigege-ui** [winezer0/APIFinderPlus#4]
<img width="534" alt="微信图片_20241211155255" src="https://github.com/user-attachments/assets/fd24f4fe-f744-4eb8-aa99-af2f1a68eb2b">

**Comment by winezer0** [comment]
确实会有这个问题，因为保存了所有响应体数据 建议每个新项目都清理一次数据库

**Comment by winezer0** [comment]
https://github.com/winezer0/APIFinderPlus/releases/tag/1.0.8 经过慎重考虑，增加数据库大于5g 自动清除原始数据的功能
