### ISSUE TITLE
【已解决】能加个规则去重吗？

### ISSUE THREAD

**Issue by tyskill** [winezer0/APIFinderPlus#5]
大佬，这个地方能不能加个内容去重的功能

<img width="777" alt="image" src="https://github.com/user-attachments/assets/3cf0f103-4785-4752-ab7a-29288e74adf4" />

**Comment by winezer0** [comment]
这个实际上匹配的时候是去重的，你这个看着也没重复呀

**Comment by tyskill** [comment]
> 这个实际上匹配的时候是去重的，你这个看着也没重复呀

不好意思，我截图的问题，主要是有重复的看上去会很别扭😂

**Comment by winezer0** [comment]
1.0.7 已添加keyword去重功能

临时下载可以访问 https://github.com/winezer0/APIFinderPlus/actions/runs/12500455095/artifacts/2362648358

**Comment by tyskill** [comment]
大佬牛逼
